<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-notices_generator for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-notices_generator
 *
 * @see Notices_Generator_Plugin::render_setting_verses()
 *
 * Variables passed:
 * @var array $verses
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<p class="description"><?php _e( 'Níže je tabulka s existujícími smutečními verši - můžete je upravovat, mazat nebo přidat nové.', Notices_Generator_Plugin::SLUG ) ?></p>
<div>
    <?php
        $idx = 1;
        foreach( $verses as $key => $verse ) :
            $verse = str_replace( "\n", " ", str_replace( "\"", "&quot;", $verse ) );
    ?>
    <p id="verse-<?php echo $key ?>" class="odwpng-settings_verses--row">
        <code><?php echo $idx ?>.</code>
        <input class="regular-text" name="odwpng_settings[verses][<?php echo $key ?>]" value="<?php echo $verse ?>" type="text">
        <button class="button"><?php _e( 'Odstranit', Notices_Generator_Plugin::SLUG ) ?></button>
    </p>
    <?php $idx++; endforeach ?>
</div>
