<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-notices_generator for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-notices_generator
 * @see Notices_Generator_Plugin::render_settings_section_1()
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<p class="description">
    <?php _e( 'Nastavení pro základní chování pluginu.', NG_SLUG ) ?>
</p>
