<?php
/**
 * @author Ondřej Doněk <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-notices_generator for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-notices_generator
 * @see NG_Plugin::render_shortcode()
 * @since 1.0.0
 *
 * Parameters passed from {@see Notices_Generator_Plugin::shortcode_notice_designer_render}:
 *
 * @var array $notice_borders Array with notice borders.
 * @var array $notice_images  Array with notice images.
 * @var array $notice_verses  Array with funeral verses.
 *
 * @todo Dokončit nahrávání fotografií zesnulého
 * @todo Dokončit ukládání do našeho CPT
 * @todo Dokončit administraci okolo našeho CPT
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<div class="notices-generator">
  <?php if( is_user_logged_in() ) : ?>
  <?php if( count( $notice_images ) === 0 ) : ?>
  <div class="notices-generator--options_error">
    <p><?php printf(
        __( 'Nejsou definované žádné obrázky, okraje či smuteční verše. V případě přetrvávajících problémů kontaktujte <a href="%s">administrátora</a>.', NG_SLUG ),
        'about:blank'
    ) ?></p>
  </div>
  <?php endif ?>
  <p class="form-notice"></p>
  <form action="" method="post" novalidate="novalidate">
    <?php wp_nonce_field( 'photo_submission' ) ?>
    <input type="hidden" name="action" value="photo_submission">
    <input type="hidden" name="photo_id">
    <div class="notices-generator--cont border border-01">
      <input id="odwpng-notice_border" name="notice-border" type="hidden" value="border01">
      <fieldset id="ngform_sec1">
        <legend>
          <?php _e( 'Obrázek a verš', NG_SLUG ) ?>
          <a href="#" class="disable-part-link disable-part-link--image_verse" title="<?php _e( 'Skrýt toto pole', NG_SLUG ) ?>"><?php _e( 'Skrýt', NG_SLUG ) ?></a>
        </legend>
        <div class="notice-image">
          <div class="notice-image--inner">
            <?php printf(
                '<img id="selected_notice_img" src="%s" title="%s">',
                ( isset( $notice_images[1] ) ) ? $notice_images[1] : '',
                __( 'Kliknutím na obrázek zobrazíte dialog pro jeho výběr.', NG_SLUG )
            ) ?>
          </div>
          <p class="description notice-image--desc">
            <?php printf( _e( 'Vyberte si obrázek kliknutím na vybraný.', NG_SLUG ) ) ?>
          </p>
        </div>
        <div class="notice-verse">
          <div class="inline-editor notice-verse--inner">
            <div class="inline-editor--inner">
              <p id="notice-verse-editor" class="inline-editor--body" contenteditable="true"><?php _e( "Kdo v naději žije, neumírá ...\n\n<em>F. Hrubín</em>", NG_SLUG ) ?></p>
            </div>
          </div>
          <p class="description notice-verse--desc"><?php printf( __( 'Vyberte si %sjiný verš%s nebo napište vlastní.', NG_SLUG ), '<span class="notice-verses-dlg-link span-link">', '</span>' ) ?></p>
        </div>
      </fieldset>
      <fieldset id="ngform_sec2">
        <legend>
          <?php _e( 'Text oznámení', NG_SLUG ) ?>
          <a href="#" class="disable-part-link disable-part-link--text" title="<?php _e( 'Skrýt toto pole', NG_SLUG ) ?>"><?php _e( 'Skrýt', NG_SLUG ) ?></a>
        </legend>
        <div class="notice-text">
          <div class="inline-editor notice-text--inner">
            <div class="inline-editor--inner">
              <p id="notice-text-editor" class="inline-editor--body" contenteditable="true"><?php _e( "S bolestí v srdci oznamujeme všem příbuzným, přátelům a známým,\nže nás navždy opustil náš milovaný ...", NG_SLUG ) ?></p>
            </div>
          </div>
          <!--<p class="description notice-text--desc"><?php _e( 'Pokud chcete zvýraznit tučně pouze část textu, dejte před něj a za něj hvězdičku, např. <strong>*Váš*</strong>', NG_SLUG ) ?></p>-->
        </div>
      </fieldset>
      <fieldset id="ngform_sec3">
        <legend>
          <?php _e( 'Jméno zesnulého', NG_SLUG ) ?>
          <a href="#" class="disable-part-link disable-part-link--deceased" title="<?php _e( 'Skrýt toto pole', NG_SLUG ) ?>"><?php _e( 'Skrýt', NG_SLUG ) ?></a>
        </legend>
        <div class="notice-deceased">
          <div class="inline-editor notice-deceased--inner">
            <div class="inline-editor--inner">
              <p id="notice-deceased-editor" class="inline-editor--body" contenteditable="true"><?php _e( "Jan Novák", NG_SLUG ) ?></p>
            </div>
          </div>
        </div>
      </fieldset>
      <fieldset id="ngform_sec4">
        <legend>
          <?php _e( 'Fotografie zesnulého', NG_SLUG ) ?>
          <a href="#" class="disable-part-link disable-part-link--photo" title="<?php _e( 'Skrýt toto pole', NG_SLUG ) ?>"><?php _e( 'Skrýt', NG_SLUG ) ?></a>
        </legend>
        <div class="notice-photo">
          <div class="inline-editor notice-photo--inner">
            <div class="inline-editor--inner">
              <p id="photo-upload-noimg"><input type="file" name="photo-upload" accept="image/*" required></p>
              <div id="photo-upload-preview"></div>
              <p id="photo-upload-notice"></p>
            </div>
          </div>
          <p class="description notice-photo--desc"><?php _e( 'Můžete nahrát fotografii zesnulého', NG_SLUG ) ?></p>
        </div>
      </fieldset>
      <fieldset id="ngform_sec5">
        <legend>
          <?php _e( 'Datum úmrtí', NG_SLUG ) ?>
          <a href="#" class="disable-part-link disable-part-link--deathdate" title="<?php _e( 'Skrýt toto pole', NG_SLUG ) ?>"><?php _e( 'Skrýt', NG_SLUG ) ?></a>
        </legend>
        <div class="notice-death_date">
          <div class="inline-editor notice-death_date--inner">
            <div class="inline-editor--inner">
              <p id="notice-death_date-editor" class="inline-editor--body" contenteditable="true"><?php _e( 'Zemřel tiše v sobotu 3. dubna 2011', NG_SLUG ) ?></p>
            </div>
          </div>
        </div>
      </fieldset>
      <fieldset id="ngform_sec6">
        <legend>
          <?php _e( 'Místo posledního rozloučení', NG_SLUG ) ?>
          <a href="#" class="disable-part-link disable-part-link--location" title="<?php _e( 'Skrýt toto pole', NG_SLUG ) ?>"><?php _e( 'Skrýt', NG_SLUG ) ?></a>
        </legend>
        <div class="notice-location">
          <div class="inline-editor notice-location--inner">
            <div class="inline-editor--inner">
              <p id="notice-location-editor" class="inline-editor--body" contenteditable="true"><?php _e( "S naším drahým zesnulým se naposledy rozloučíme v pátek 15. dubna 2011\nv malé obřadní síni krematoria v ...", NG_SLUG ) ?></p>
            </div>
          </div>
        </div>
      </fieldset>
      <fieldset id="ngform_sec7">
        <legend>
          <?php _e( 'Jménem pozůstalých', NG_SLUG ) ?>
          <a href="#" class="disable-part-link disable-part-link--survivors_text" title="<?php _e( 'Skrýt toto pole', NG_SLUG ) ?>"><?php _e( 'Skrýt', NG_SLUG ) ?></a>
        </legend>
        <div class="notice-survivors_text">
          <div class="inline-editor notice-survivors_text--inner">
            <div class="inline-editor--inner">
              <p id="notice-survivors_text-editor" class="inline-editor--body" contenteditable="true"><?php _e( 'Jménem pozůstalých', NG_SLUG ) ?></p>
            </div>
          </div>
        </div>
      </fieldset>
      <fieldset id="ngform_sec8">
        <legend>
          <?php _e( 'Pozůstalí', NG_SLUG ) ?>
          <a href="#" class="disable-part-link disable-part-link--survivors" title="<?php _e( 'Skrýt toto pole', NG_SLUG ) ?>"><?php _e( 'Skrýt', NG_SLUG ) ?></a>
        </legend>
        <div id="ng-survivors-panel-1" class="notice-survivors panel-left">
          <div class="inline-editor notice-survivors--inner">
            <div class="inline-editor--inner">
              <p id="notice-survivors-editor" class="inline-editor--body" contenteditable="true"><?php _e( "Manželka<br>Dcera s rodinou<br>Syn s rodinou", NG_SLUG ) ?></p>
            </div>
          </div>
        </div>
        <div id="ng-survivors-panel-2" class="notice-survivors panel-right">
          <div class="inline-editor notice-survivors--inner">
            <div class="inline-editor--inner">
              <p id="notice-survivors-editor-2" class="inline-editor--body" contenteditable="true"><?php _e( "Bratr s rodinou<br>Vnoučata a synovci", NG_SLUG ) ?></p>
            </div>
          </div>
        </div>
        <div class="notice-survivors--form">
          <label><?php _e( 'Zobrazit jako: ', NG_SLUG ) ?></label>
          <label class="notice-radio">
            <input type="radio" name="ng-survivors-columns" value="1">
            <?php _e( 'jeden sloupec', NG_SLUG ) ?>
          </label>
          <label class="notice-radio">
            <input type="radio" name="ng-survivors-columns" value="2" checked="checked">
            <?php _e( 'dva sloupce', NG_SLUG ) ?>
          </label>
        </div>
      </fieldset>
      <fieldset id="ngform_sec9">
        <legend>
          <?php _e( 'Projevy a soustrasti', NG_SLUG ) ?>
          <a href="#" class="disable-part-link disable-part-link--thanks" title="<?php _e( 'Skrýt toto pole', NG_SLUG ) ?>"><?php _e( 'Skrýt', NG_SLUG ) ?></a>
        </legend>
        <div class="notice-thanks">
          <div class="inline-editor notice-thanks--inner">
            <div class="inline-editor--inner">
              <p id="notice-thanks-editor" class="inline-editor--body" contenteditable="true"><?php _e( 'Za projevy soustrasti děkujeme', NG_SLUG ) ?></p>
            </div>
          </div>
        </div>
      </fieldset>
      <fieldset id="ngform_sec10">
        <legend>
          <?php _e( 'Adresa', NG_SLUG ) ?>
          <a href="#" class="disable-part-link disable-part-link--address" title="<?php _e( 'Skrýt toto pole', NG_SLUG ) ?>"><?php _e( 'Skrýt', NG_SLUG ) ?></a>
        </legend>
        <div class="notice-address">
          <div class="inline-editor notice-address--inner">
            <div class="inline-editor--inner">
              <p id="notice-address-editor" class="inline-editor--body" contenteditable="true"><?php _e( "Vaše adresa", NG_SLUG ) ?></p>
            </div>
          </div>
        </div>
      </fieldset>
    </div>
    <p class="buttons">
      <span id="odwpng-button_print" class="button button-primary"><?php _e( 'Pokračovat', NG_SLUG ) ?></span>
      <span id="odwpng-button_preview" class="button button-primary"><?php _e( 'Náhled', NG_SLUG ) ?></span>
      <span id="odwpng-button_borders" class="button button-secondary"><?php _e( 'Vybrat ohraničení', NG_SLUG ) ?></span>
    </p>
  </form>
  <div id="notice-images-dlg" class="dlg-container">
    <div class="dlg-header">
      <h3><?php _e( 'Vyberte obrázek', NG_SLUG ) ?></h3>
    </div>
    <div class="dlg-body">
      <ul class="images-list">
        <?php foreach( $notice_images as $image ) : ?>
        <li class="images-item">
          <span class="images-item--cont">
            <img src="<?php echo $image ?>" title="<?php printf( __( 'Vyberte obrázek %s.', NG_SLUG ), $image ) ?>">
          </span>
        </li>
        <?php endforeach ?>
      </ul>
    </div>
    <div class="dlg-footer">
        <span class="button button-cancel"><?php _e( 'Zrušit', NG_SLUG ) ?></span>
    </div>
  </div>
  <div id="notice-verses-dlg" class="dlg-container">
    <div class="dlg-header">
      <h3><?php _e( 'Vyberte smuteční verš', NG_SLUG ) ?></h3>
    </div>
    <div class="dlg-body">
      <ul class="verses-list">
        <?php foreach( $notice_verses as $verse ) : ?>
        <li class="verses-item"><?php echo str_replace( "\n", ' ', $verse ) ?></li>
        <?php endforeach ?>
      </ul>
    </div>
    <div class="dlg-footer">
      <span class="button button-cancel"><?php _e( 'Zrušit', NG_SLUG ) ?></span>
    </div>
  </div>
  <div id="notice-borders-dlg" class="dlg-container">
    <div class="dlg-header">
      <h3><?php _e( 'Vyberte ohraničení', NG_SLUG ) ?></h3>
    </div>
    <div class="dlg-body">
      <ul class="borders-list">
        <li class="borders-item border border-01" title="<?php _e( 'Vyberte okraj 1', NG_SLUG ) ?>"><?php _e( '01', NG_SLUG ) ?></li>
        <li class="borders-item border border-02" title="<?php _e( 'Vyberte okraj 2', NG_SLUG ) ?>"><?php _e( '02', NG_SLUG ) ?></li>
        <li class="borders-item border border-03" title="<?php _e( 'Vyberte okraj 3', NG_SLUG ) ?>"><?php _e( '03', NG_SLUG ) ?></li>
        <li class="borders-item border border-04" title="<?php _e( 'Vyberte okraj 4', NG_SLUG ) ?>"><?php _e( '04', NG_SLUG ) ?></li>
      </ul>
    </div>
    <div class="dlg-footer">
      <span class="button button-cancel"><?php _e( 'Zrušit', NG_SLUG ) ?></span>
    </div>
  </div>
  <?php else : ?>
  <div class="notices-generator--auth_error">
    <p><?php printf(
      __( 'Pro zobrazení generátoru smutečních oznámení musíte být přihlášeným uživatelem. Pro více informací kontaktujte <a href="%s">administrátora</a>.', NG_SLUG ),
      'about:blank'
    ) ?></p>
  </div>
  <?php endif ?>
</div>
